a = {
   "_id": "ObjectId(64dab16d54c7a62a42333a11)",
   "id": 629,
   "name": "K. De Bruyne",
   "firstname": "Kevin",
   "lastname": "De Bruyne",
   "age": 32,
   "birth": {"date": "1991-06-28", "place": "Drongen", "country": "Belgium"},
   "nationality": "Belgium",
   "height": "181 cm",
   "weight": "68 kg",
   "injured": False,
   "photo": "https://media-3.api-sports.io/football/players/629.png",
   "team": {
       "id": 50,
       "name": "Manchester City",
       "logo": "https://media-1.api-sports.io/football/teams/50.png",
   },
   "league": {
       "id": 39,
       "name": "Premier League",
       "country": "England",
       "logo": "https://media-2.api-sports.io/football/leagues/39.png",
       "flag": "https://media-3.api-sports.io/flags/gb.svg",
       "season": 2020,
   },
   "games": {
       "appearences": 25,
       "lineups": 23,
       "minutes": 2001,
       "number": None,
       "position": "Midfielder",
       "rating": "7.784000",
       "captain": False,
   },
   "substitutes": {"in": 2, "out": 6, "bench": 6},
   "shots": {"total": 53, "on": 27},
   "goals": {"total": 6, "conceded": 0, "assists": 12, "saves": None},
   "passes": {"total": 1263, "key": 81, "accuracy": 41},
   "tackles": {"total": 34, "blocks": 1, "interceptions": 9},
   "duels": {"total": 239, "won": 117},
   "dribbles": {"attempts": 67, "success": 48, "past": None},
   "fouls": {"drawn": 31, "committed": 27},
   "cards": {"yellow": 1, "yellowred": 0, "red": 0},
   "penalty": {"won": None, "commited": None, "scored": 2, "missed": 1, "saved": None},
}


print(a["name"])